lab_1/urls.py
from django.urls import path
from .views import *
#url for app
app_name = "home"

urlpatterns = [
    path('', homepage, name='home'),
    path('about', about, name='about'),
    path('education', education, name='education'),
    path('achievement', achievement, name='achievement'),
    path('project', project, name='project'),
    path('comment', comment, name='comment'),
    path('time', timezone),
    path('project_list', project_list, name='project_list'),
    path('delete/<int:pk>', project_delete, name="delete"),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab_1.urls')),
]

lab_1/models.py
from django.db import models

# Create your models here.
class CommentModel(models.Model):
    email = models.EmailField(max_length=250)
    comment = models.TextField()

    def __str__(self):
        return f"{self.email} comment"

class ProjectModel(models.Model):
    
    title = models.CharField(max_length=200)
    date_start = models.DateField()
    date_end = models.DateField()
    description = models.CharField(default="",max_length=200)
    place = models.CharField(max_length=200)
    category = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.title}"

lab_1/forms.py
from django import forms
from lab_1.models import CommentModel, ProjectModel
import datetime

class CommentForm(forms.ModelForm):
    # <input id="email" type="email" class="validate">
    email = forms.CharField(label="", widget=forms.TextInput(
        attrs = {
                "id" : "email",
                'class' : 'validate',
                'type' : 'email'
                }
    ))
    # <textarea id="textarea1" class="materialize-textarea"></textarea>
    comment = forms.CharField(label="", widget=forms.Textarea(
    attrs = {
            "id" : "textarea1",
            'class' : 'materialize-textarea',
            }
    ))
    class Meta:
        model = CommentModel
        fields = ("email", "comment")

class ProjectForm(forms.ModelForm):
    title = forms.CharField(label="Project Title", widget=forms.TextInput(
        attrs = {
                "id" : "email",
                }
    ))
    category = forms.CharField(label="Project Type", widget=forms.TextInput(
        attrs = {
                "id" : "email",
                }
    ))
    description = forms.CharField(label="Project Type", widget=forms.TextInput(
        attrs = {
                "id" : "email",
                }
    ))
    date_start =  forms.DateField(input_formats=['%Y-%m-%d'], initial=datetime.date.today(),widget=forms.TextInput(attrs=
                                {
                                    'class':'datepicker'
                                }))

    date_end =  forms.DateField(input_formats=['%Y-%m-%d'], initial=datetime.date.today(),widget=forms.TextInput(attrs=
                                {
                                    'class':'datepicker'
                                }))
    class Meta:
        model = ProjectModel
        fields = ('title','date_start','date_end','place','category','description')

lab_1/views.py
from django.shortcuts import render, redirect
from lab_1.forms import CommentForm, ProjectForm
from lab_1.models import CommentModel, ProjectModel
import datetime

def homepage(request):
    now = datetime.datetime.now()
    return render(request, 'homepage.html')
def about(request):
    return render(request, 'about.html')

def education(request):
    return render(request, 'education.html')

def achievement(request):
    return render(request, 'achievment.html')

def project(request):
    return render(request, 'project.html')

def comment(request):
    form = CommentForm(request.POST)
    if request.method == "POST" and form.is_valid():
        instance = form.save()
        return redirect('home:home')
    return render(request, 'comment.html', {
        "form" : CommentForm(),
        "comment" : CommentModel.objects.all(),
    })
def timezone(request):
    now = datetime.datetime.now()
    print(now)
    return render(request, '../templates/base.html', {
        'time':now, "test":"Hello",
    })

def project_list(request):
    form = ProjectForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            instance = form.save()
            print(request.POST)
            return redirect('home:project_list')
    return render(request, 'story5.html', {
        'form':ProjectForm(),
        'project': ProjectModel.objects.all(),
    })

def project_delete(request,pk):
    project = ProjectModel.objects.get(pk=pk)
    if request.method == "POST" :
        project.delete()
        return redirect("home:project_list") 

lab_1/templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block body %}
  <!-- body -->
  <div class="container-body row">
    <div class="col s12 m6 l6 xl6 container-img about valign-wrapper">
        <h1 class="judul" style="font-size:7rem">About</h1>
    </div>
    <div class="col s12 m6 l6 xl6 valign-wrapper menu">
      <div class="card valign-wrapper" id="content">
        <p></p>
      </div>
    
    </div>

  </div>  
<!-- body -->
{% endblock body %}
  
    
{% block js %}
    <script>
      $(document).ready(function(){
        $(".judul").fadeIn(200);
      });

      var aText = new Array(
        "Hello,my name is Anggardha Febriano, people usually call me Angga or Anggardha. I was born 25 February 2000 in Jogjakarta.I'm an optimistic person with a big dreams that i want to reach.I like sport very much, escpecially Futsal and Taekwondo. Thank You for Visiting my Website!"
        );
        var iSpeed = 50; // time delay of print out
        var iIndex = 0; // start printing array at this posision
        var iArrLength = aText[0].length; // the length of the text array
        var iScrollAt = 20; // start scrolling up at this many lines
        
        var iTextPos = 0; // initialise text position
        var sContents = ''; // initialise contents variable
        var iRow; // initialise current row
        
        function typewriter()
        {
        sContents =  ' ';
        iRow = Math.max(0, iIndex-iScrollAt);
        var destination = document.getElementById("content");
        
        while ( iRow < iIndex ) {
          sContents += aText[iRow++] + '<br />';
        }
        destination.innerHTML = sContents + aText[iIndex].substring(0, iTextPos) + "_";
        if ( iTextPos++ == iArrLength ) {
          iTextPos = 0;
          iIndex++;
          if ( iIndex != aText.length ) {
          iArrLength = aText[iIndex].length;
          setTimeout("typewriter()", 100);
          }
        } else {
          setTimeout("typewriter()", iSpeed);
        }
        }


      typewriter();
      
      </script>  
{% endblock js %}
    
    
       
    

lab_1/templates/achievment.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% block body %}
  <!-- body -->
<div class="container-challenge row">
  <div class="col s12 m6 l6 xl6 container-img prestasi valign-wrapper">
      <h1 class="judul" id="achievment" style="font-size:3.5rem">Achievement</h1>
  </div>
  <div class="col s12 m6 l6 xl6 valign-wrapper menu">
    <div class="card" id="content">
          <ul class="collapsible">
                  <li class="active">
                      <div class="collapsible-header"><i class="material-icons">stars</i>
                      <p id="pres">Olimpiade Sains Nasional bidang Biologi tingkat kota(2017, Peringkat 3)</p>
                      </div>
                      <div class="collapsible-body">
                      <p id="pres">
                              Olimpiade Sains Nasional adalah ajang berkompetisi dalam bidang sains bagi para siswa pada jenjang SD, SMP, dan SMA di Indonesia. Siswa yang mengikuti Olimpiade Sains Nasional adalah siswa yang telah lolos seleksi tingkat kabupaten dan provinsi dan adalah siswa-siswa terbaik dari provinsinya masing-masing.
                      </p>
                      </div>
                  </li>
                  <li>
                      <div class="collapsible-header"><i class="material-icons">stars</i>
                      <p id="pres">Jakarta Taekwondo Festival 2008(Medali Perak-Kyorugi)</p>
                      </div>
                      <div class="collapsible-body">
                      <p id="pres">
                              Kejuaraan yang diselenggarakan Pengurus Besar Taekwondo Indonesia ini merupakan wadah dan kreativitas bagi anak usia dini hingga pemuda. Dalam kejuaraan ini peserta dari umur enam hingga 18 tahun saling bertarung untuk meningkatkan prestasi olahraga, khususnya taekwondo di Tanah Air.setiap tahunnya peserta yang mengikuti kejuaraan ini lebih dari 2000 peserta
                      </p>
                      </div>
                  </li>
                  <li>
                      <div class="collapsible-header"><i class="material-icons">stars</i>
                      <p id="pres">Jakarta Taekwondo Festival 2009(Medali Emas-Kyorugi)</p>
                      </div>
                      <div class="collapsible-body">
                      <p id="pres">
                              Kejuaraan yang diselenggarakan Pengurus Besar Taekwondo Indonesia ini merupakan wadah dan kreativitas bagi anak usia dini hingga pemuda. Dalam kejuaraan ini peserta dari umur enam hingga 18 tahun saling bertarung untuk meningkatkan prestasi olahraga, khususnya taekwondo di Tanah Air.setiap tahunnya peserta yang mengikuti kejuaraan ini lebih dari 2000 peserta
                      </p>
                      </div>
                  </li>
                  <li>
                      <div class="collapsible-header"><i class="material-icons">stars</i>
                      <p id="pres">Jakarta Taekwondo Festival 2016(Medali Perak-Poomsae)</p>
                      </div>
                      <div class="collapsible-body">
                      <p id="pres">
                              Kejuaraan yang diselenggarakan Pengurus Besar Taekwondo Indonesia ini merupakan wadah dan kreativitas bagi anak usia dini hingga pemuda. Dalam kejuaraan ini peserta dari umur enam hingga 18 tahun saling bertarung untuk meningkatkan prestasi olahraga, khususnya taekwondo di Tanah Air.setiap tahunnya peserta yang mengikuti kejuaraan ini lebih dari 2000 peserta
                      </p>
                      </div>
                  </li>
                  <li>
                      <div class="collapsible-header"><i class="material-icons">stars</i>
                      <p id="pres">Pekan Olahraga Kota Depok ke 5(Taekwondo-Poomase, Medali Perunggu)</p>
                      </div>
                      <div class="collapsible-body">
                      <p id="pres">
                              Event Olahraga terbesar yang diselenggarakan oleh Pemerintah Kota Depok yang diselenggarakan tiap 2 tahun. PORKOT mempertemukan atlet atlet muda depok yang setiap atlet mewakili kecamatannya masing masing
                      </p>
                      </div>
                  </li>
                  <li>
                      <div class="collapsible-header"><i class="material-icons">people</i>
                      <p id="pres">Ketua Ekskul Taekwondo SMAN 1 Depok(2017-2018)</p>
                      </div>
                      <div class="collapsible-body">
                      <p id="pres">
                              Menjadi ketua ekskul Taekwondo di SMAN 1 Depok selama periode 2017-2018
                      </p>
                      </div>
                  </li>
                  <li>
                      <div class="collapsible-header"><i class="material-icons">people</i>
                      <p id="pres">Panitia Olimpiade UI 2018</p>
                      </div>
                      <div class="collapsible-body">
                      <p id="pres">
                              Menjadi staff olimpide UI bidang Taekwondo
                      </p>
                      </div>
                  </li>
                  <li>
                      <div class="collapsible-header"><i class="material-icons">people</i>
                      <p id="pres">Panitia Pemira Fasilkom UI 2018</p>
                      </div>
                      <div class="collapsible-body">
                      <p id="pres">
                              Menjadi staff Verifikasi dan Pengawasan Pemira Fasilkom UI
                      </p>
                      </div>
                  </li>
                </ul>
                      
                          
    </div>
  </div>
  </div>
</div>  
<!-- body -->

{% endblock body %}
  

{% block js %}
  <script>
      $(document).ready(function(){
        $(".judul").fadeIn(200);
        $('.collapsible').collapsible();
      });
  </script>
{% endblock js %}
  
    

lab_1/templates/comment.html
   {% extends 'base.html' %}
   {% load staticfiles %}
   {% load static %}
   
   {% block body %}
    <!-- body -->
    <div class="container-body row">
      <div class="col s12 m6 l6 xl6 container-img proyek valign-wrapper">
          <h1 class="judul" id="project" style="font-size:6rem">Comment</h1>
      </div>
      <div class="col s12 m6 l6 xl6 valign-wrapper menu">
        <div class="card" id="content" style="padding-top:100px">
              <div class="row">
                      <form class="col s12" method="POST">
                        {% csrf_token %}
                        <div class="row">
                          <div class="input-field col s12">
                            {{form.email}}
                            <label for="email">Email</label>
                            <span class="helper-text" data-error="wrong" data-success="right"></span>
                          </div>
                          <div class="row">
                                  <div class="input-field col s12">
                                    {{form.comment}}
                                    <label for="textarea1">Comment</label>
                                  </div>
                                </div>
                        </div>
                        <button type="submit" class="btn center orange">Submit</button>
                      </form>
                      <div class="col s12">
                        <h1>All Comment</h1>
                          {% for c in comment %}
                              <h4 class="left-align">{{c.email}}</h4>
                              <h4 style="font-size:20px;" class="left-align">{{c.comment}}</h4>
                          {% empty %}
                            <h4>No comment yet</h4>
                          {% endfor %}
                      </div>
                    </div>
          </div>
      </div>
    </div>  
  <!-- body --> 
   {% endblock body %}
     
   
   {% block js %}
     
   {% endblock js %}
     
    

lab_1/templates/education.html
    {% extends 'base.html' %}
    {% load staticfiles %}
    {% load static %}
    
    {% block body %}
      <!-- body -->
      <div class="container-body row">
        <div class="col s12 m6 l6 xl6 container-img education valign-wrapper">
            <h1 class="judul" style="font-size:4rem;color: black">Education</h1>
        </div>
        <div class="col s12 m6 l6 xl6 valign-wrapper menu">
            <div class="card" id="content">
            <div id="edu-list" class="aniview" data-av-animation="fadeInRight">
                <h3 id="edu">SD<i class="material-icons" style="color: green;">sentiment_very_satisfied</i></h3>
                <p>
                  SDI Al-Fauzien <br>
                  2006-2012</p>
                <h3 id="edu">SMP<i class="material-icons" style="color: green;">sentiment_very_satisfied</i></h3>
                <p>
                  SMPN 3 Depok <br>
                  2012-2015</p>
                <h3 id="edu">SMA<i class="material-icons" style="color: green;">sentiment_very_satisfied</i></h3>
                <p>
                  SMAN 1 Depok <br>
                  2006-2012</p>
                <h3 id="edu">Sarjana<i class="material-icons" style="color: orange;">sentiment_satisfied</i></h3>
                <p>
                  Universitas Indonesia <br>
                  2006-2012</p>
            </div>
            </div>
        </div>
      </div>  
    <!-- body -->
    {% endblock body %}
      
    
    {% block js %}
          <!--JavaScript at end of body for optimized loading-->
    
    <script>
      $(document).ready(function(){
        $(".judul").fadeIn(200);
        $('.aniview').AniView();
      });      
  </script>
  <script src="{% static 'js/jquery.aniview.js' %}"></script>   
  {% endblock js %}
      

lab_1/templates/homepage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}



{% block body %}
<div class="container-body row">
  <div class="col s12 m6 l6 xl6 container-img home">
    <div class="row hide-on-med-and-up">
    <div id="judul-mobile" class="col s12 container-menu hide-on-med-and-up" style="margin-top:20%;">
        <h1 id="judul" style="margin-top:40px;font-size: 3em" class="center-align">Welcome To My Website</h1>
        <a id="link" class="btn orange" href="{% url 'home:about' %}">About<i class="material-icons right">arrow_forward</i></a><br>
        <a id="link" class="btn orange" href="{% url 'home:education' %}">Education<i class="material-icons right">arrow_forward</i></a><br>
        <a id="link" class="btn orange" href="{% url 'home:achievement' %}">Achievment<i class="material-icons right">arrow_forward</i></a><br>
        <a id="link" class="btn orange" href="{% url 'home:project' %}">Project<i class="material-icons right">arrow_forward</i></a><br>
        <a id="link" class="btn orange" href="{% url 'home:comment' %}">Comment<i class="material-icons right">arrow_forward</i></a><br>
        <a id="link" class="btn orange" href="{% url 'home:project_list' %}">Project List<i class="material-icons right">arrow_forward</i></a><br>
        <!-- test -->
        <!-- <a id="link" class="btn orange" href="registration.html">SignUp<i class="material-icons right">arrow_forward</i></a><br> -->
        <p class="center-align">Contact me at anggardhanoano@gmail.com</p>
  </div>
  </div>
  </div>
  <div class="col s12 m6 l6 xl6 valign-wrapper menu hide-on-small-only">
    <div class="container-menu">
          <h1 id="judul" style="margin-top:-20px;" class="center-align">Welcome To My Website</h1>
          <a id="link" class="btn orange" href="{% url 'home:about' %}">About<i class="material-icons right">arrow_forward</i></a><br>
          <a id="link" class="btn orange" href="{% url 'home:education' %}">Education<i class="material-icons right">arrow_forward</i></a><br>
          <a id="link" class="btn orange" href="{% url 'home:achievement' %}">Achievment<i class="material-icons right">arrow_forward</i></a><br>
          <a id="link" class="btn orange" href="{% url 'home:project' %}">Project<i class="material-icons right">arrow_forward</i></a><br>
          <a id="link" class="btn orange" href="{% url 'home:comment' %}">Comment<i class="material-icons right">arrow_forward</i></a><br>
          <a id="link" class="btn orange" href="{% url 'home:project_list' %}">Project List<i class="material-icons right">arrow_forward</i></a><br>
          <!-- <a id="link" class="btn orange" href="registration.html">SignUp<i class="material-icons right">arrow_forward</i></a><br> -->
          <p class="center-align">Contact me at anggardhanoano@gmail.com</p>
    </div>
  </div>
  </div>
{% endblock body %}


{% block js %}
  
{% endblock js %}
  
  

lab_1/templates/project.html
   {% extends 'base.html' %}
   {% load staticfiles %}
   {% load static %}
   {% block body %}
     <!-- body -->
     <div class="container-body row">
      <div class="col s12 m6 l6 xl6 container-img proyek valign-wrapper">
          <h1 class="judul" id="project" style="font-size:5rem">Project</h1>
      </div>
      <div class="col s12 m6 l6 xl6 valign-wrapper menu">
        <div class="card" id="content">
              <div class="carousel">
                      <div class="carousel-item">
                        <div class="card">
                          <div class="card-image">
                            <img src="{% static 'img/image.png' %}">
                          </div>
                  
                          <div class="card-content">
                              <p style="font-size:20px;">Portofolio Page Project</p>
                              <p style="font-size:15px;">Made with django and materialize css framework</p>
                          </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <div class="card">
                          <div class="card-image">
                            <img src="{% static 'img/U.png' %}">
                          </div>
                          <div class="card-content">
                              <p style="font-size:20px;">Uneev Coming Soon Page</p>
                              <p style="font-size:15px;">Made with django and materialize css framework. Visitor can submit their email so they can get update from uneev.id</p>
                          </div>
                        </div>
                      </div>
                      <div class="carousel-item">
                        <div class="card">
                          <div class="card-image">
                            <img src="{% static 'img/code.png' %}">
                          </div>
                          <div class="card-content">
                                  <p style="font-size:20px;">Uneev Main Web</p>
                                  <p style="font-size:15px;">Made with django and materialize css framework. The description of this page is still top-secret, but you can visit <a href="https://uneev.id">Uneev.id</a> for more information</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    </div>
      </div>
    </div>  
  <!-- body -->
   {% endblock body %}
     
    {% block js %}
      <!--JavaScript at end of body for optimized loading-->
    <script>
      $(document).ready(function(){
        $(".judul").fadeIn(200);
        $('.carousel').carousel();
      });
  </script>
    {% endblock js %}
      
    
       

lab_1/templates/registration.html
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link rel="shortcut icon" href="../static/img/image.png" />
    <title>Anggardha - SignUp</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="../static/css/base.css">
    <link href="https://fonts.googleapis.com/css?family=Waiting+for+the+Sunrise" rel="stylesheet" type="text/css"/>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <!-- header -->
    <nav class="nav-extended" style="background-color:transparent;box-shadow: none;" onmouseout="clearCoor()" onmousemove="showCoords(event)" >
        <div   class="nav-wrapper" id="navbar">
          
          <a href="homepage.html" class="brand-logo center"><img src="../static/img/image.png" id="logo-image"></a>
          
        </div>
        </div>
      </nav>
    <!-- header -->
    <!-- body -->
      <div class="container-body row">
        <h1 class="center-align" style="margin-bottom:-40px;">Create Account</h1>
        <div class="col s12 m12 l12 xl12 container-img valign-wrapper">
            <div class="row">
                <form class="col s12">
                  <div class="row">
                    <div class="input-field col s6">
                      <i class="material-icons prefix">account_circle</i>
                      <input id="first_name" type="text" class="validate">
                      <label for="first_name">First Name</label>
                    </div>
                    <div class="input-field col s6">
                      <input id="last_name" type="text" class="validate">
                      <label for="last_name">Last Name</label>
                    </div>
                  </div>
                  <div class="row">
                    <div class="input-field col s12">
                        <i class="material-icons prefix">info</i>
                      <input id="password" type="password" class="validate">
                      <label for="password">Password</label>
                    </div>
                  </div>
                  <div class="row">
                    <div class="input-field col s12">
                      <i class="material-icons prefix">email</i>
                      <input id="email" type="email" class="validate">
                      <label for="email">Email</label>
                    </div>
                  </div>
                  <div class="file-path-wrapper hide">
                    <input class="file-path validate" type="text" placeholder="Upload your course poster">
                  </div>
                  <button class="btn orange" id="sign-btn">SignUp</button>
                </form>
              </div>   
        </div>
        <footer class="col s12 m12 l12 xl12 center-align" style="color:white" id="footer">
            Copyright Anggardha Febriano 2019
    </footer>
      </div>  
    <!-- body -->
    <!--JavaScript at end of body for optimized loading-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script> 
    <script>
        $(document).ready(function(){
          $(".judul").fadeIn(200);
          $('.collapsible').collapsible();
        });
                
        function showCoords(event) {
          $("#navbar").css('border-radius',"0px 0px 0px 0px");
          $("#nav-tab").fadeIn(500);
        }
        
        function clearCoor() {
          console.log("kosong")
          $("#nav-tab").fadeOut(500);
          $("#navbar").css('border-radius',"0px 0px 100% 100%");
        }        
        </script>
       
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

lab_1/templates/story5.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
<div class="container-body row">
        <div class="col s12 m6 l6 xl6 container-img proyek valign-wrapper">
            <h1 class="judul" id="project" style="font-size:6rem">Comment</h1>
        </div>
        <div class="col s12 m6 l6 xl6 valign-wrapper menu">
          <div class="card" id="content" style="padding-top:100px">
                <div class="row">
                        <form class="col s12" method="POST">
                          {% csrf_token %}
                          <div class="row">
                            <div class="input-field col s12">
                            <p class="left-align">Title</p>
                              {{form.title}}
                              <p class="left-align">Category</p>
                              {{form.category}}
                              <p class="left-align">Short Description</p>
                              {{form.description}}
                              <p class="left-align">Place</p>
                              {{form.place}}
                              <p class="left-align">Start Date</p>
                              {{form.date_start}}
                              <p class="left-align">End Date</p>
                              {{form.date_end}}
                            </div>
                          <button type="submit" class="btn center orange">Submit</button>
                        </form>
                        <div class="col s12">
                          <h1>All Projects</h1>
                            {% for p in project %}
                                <h4 class="left-align">Title : {{p.title}}</h4>
                                <h4 class="left-align">Category : {{p.category}}</h4>
                                <h4 class="left-align">Description : {{p.description}}</h4>
                                <h4 class="left-align">Place : {{p.place}}</h4>
                                <h4 style="font-size:20px;" class="left-align">{{p.date_start}} - {{p.date_end}}</h4>
                                <a class="waves-effect waves-light btn modal-trigger red" href="#modal1">Delete</a>
                                <div id="modal1" class="modal">
                                  <div class="modal-content">
                                    <h4>Confirmation</h4>
                                    <p>Are You Sure Want to Delete This Project?</p>
                                  </div>
                                  <div class="modal-footer">
                                    <form method="POST" action="{% url 'home:delete' pk=p.pk %}">
                                      {% csrf_token %}
                                    <button type="submit" class="modal-close waves-effect btn-flat red">Delete</button>
                                    <a class="modal-close waves-effect btn-flat orange">Cancel</a>
                                  </form>
                                  </div>
                                </div>
                                <hr>
                            {% empty %}
                              <h4>No project yet</h4>
                            {% endfor %}
                        </div>
                      </div>
            </div>
        </div>
      </div>  
  
{% endblock body %}
    

{% block js %}
    <script>
  $(document).ready(function(){
    $('.datepicker').datepicker(
      {format : 'yyyy-mm-dd'}
    );
  });
  $(document).ready(function(){
    $('.modal').modal();
  });
    </script>
{% endblock js %}
    

templates/footer.html
{% load static %}


{% block footer %}
<footer class="col s12 m12 l12 xl12 center-align" style="color:white" id="footer">
        Copyright Anggardha Febriano 2019
      </footer>
{% endblock footer %}
    

templates/header.html
{% load static %}
<nav class="nav-extended" style="background-color:transparent;box-shadow: none;" onmousemove="showCoords(event)" >
        <div   class="nav-wrapper" id="navbar">
          
          <a href="{% url 'home:home' %}" class="brand-logo center">
            <img src="{% static 'img/image.png' %}" id="logo-image">
            <span style="font-size: 1rem;display: block;position: absolute;top:10px;left:-2px">Home</span>
          </a>
          
        </div>
        <div class="nav-content row" id="nav-tab" onmouseout="clearCoor()">
          <div class="col s12 m12 l12 xl12">
          <ul class="tabs tabs-transparent">
            <li class="tab col s3 m3 l3 xl3"><a href="{% url 'home:about' %}">About Me</a></li>
            <li class="tab col s3 m3 l3 xl3"><a href="{% url 'home:education' %}">Education</a></li>
            <li class="tab col s3 m3 l3 xl3"><a href="{% url 'home:achievement' %}">Achievment</a></li>
            <li class="tab col s3 m3 l3 xl3"><a href="{% url 'home:project' %}">Project</a></li>
          </ul>
        </div>
        </div>
      </nav>
    